import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "@lib/services/ClientProvider";
import ErrorCatchService from "@/lib/services/ErrorCatchService";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body dir="rtl" className={inter.className}>
        <ClientProvider>
          {children}
          {/* <ErrorCatchService>{children} </ErrorCatchService> */}
        </ClientProvider>
      </body>
    </html>
  );
}
